### PR TITLE
Parse enr contents as rlp objects

### LINKED ISSUE #3: Can't parse Geth node's ENR
I find it can't parse Geth node's ENR like this:
``` 
enr:-Je4QIdx4eWpaemy4ECbJU2ZsXvzX3XsiF10QOjm-87XBkoaJdEq3qjijY7fMkhP1SZRUeqHodSczUCuj01eWWzQ2xc7g2V0aMfGhOAp6ZGAgmlkgnY0gmlwhLecb4iJc2VjcDI1NmsxoQPnve6T4T8AWndeYCCi-zJncpl_W_SR8Wky_rUI8MxR24N0Y3CCdmCDdWRwgnZg
```
I get Error `Custom("List decode fail")`
But It can be parsed well by Geth.

### PR DESCRIPTION
**Pull request by pawanjay176**
Fixes #3 

## Proposed changes

Instead of storing rlp encoding of content values as suggested in #5 , this PR changes `decode` to iterate over the rlp list from the raw bytes and interpret each element as a rlp data item. This way, all key value pairs are interpreted as rlp data items instead of bytes.
Tested it on all all enrs in https://github.com/ethereum/discv4-dns-lists/blob/master/all.json and was able to decode all of them.
Added a test case from the above link which was failing before because of interpreting as bytes.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -826,16 +823,16 @@ impl<K: EnrKey> rlp::Decodable for Enr<K> {
         let mut content = BTreeMap::new();
         let mut prev: Option<String> = None;
         for _ in 0..decoded_list.len() / 2 {
-            let key = decoded_list.remove(0);
-            let value = decoded_list.remove(0);
+            let key = decoded_list.remove(0).data()?;
+            let value = decoded_list.remove(0).data()?;
```
Comment (AgeManning) [inline src/lib.rs:827]: My concern was this being a recursive list, we strip off the rlp header here. But when interpreting a specific field, I guess we can always account for that.

**Review by AgeManning — APPROVED** [review]
Nice work
